query User($id: String!) {
  user(id: $id) {
    id
    username
  }
}

mutation UpdateUser($updateUserInput: UpdateUserInput!) {
  updateUser(updateUserInput: $updateUserInput) {
    id
    username
  }
}
